meson: support building docs
kaniini/libucontext pull request #49
Opened 2022-09-28 23:15 UTC by matoro

Toggleable with -Ddocs=(true|false), defaults to false.

Requires bumping minimum meson version to 0.59.0, or 0.61.0 to also include symlinks.

2022-09-29 00:51 UTC, eli-schwartz requested changes

2022-09-29 00:51 UTC, eli-schwartz commented on doc/meson.build
> +  install_dir: 'share/man/man3'
```suggestion
  install_dir: get_option('mandir') / 'man3'
```

2022-09-29 00:51 UTC, eli-schwartz commented on doc/meson.build
> +      install_dir: 'share/man/man3'
```suggestion
      install_dir: get_option('mandir') / 'man3'
```

2022-09-29 00:55 UTC, matoro commented
Thanks Eli!  Did not know that mandir was automatically calculated.

2022-09-29 01:20 UTC, eli-schwartz commented
It's a builtin directory variable similar to --prefix and --libdir, in this case --mandir. So in order to support OS layout, that option should be respected.
(There's also an --infodir option for GNU texinfo.)

2023-05-19 01:13 UTC, kaniini commented
Merged, thanks

2023-05-19 01:13 UTC, closed without merging